# Generated by Django 5.2.1 on 2025-05-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("productId", models.IntegerField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=50)),
                ("upc", models.CharField(max_length=50)),
                ("productName", models.CharField(max_length=255)),
                ("availableQuantity", models.IntegerField()),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("imageUrl", models.URLField(max_length=500)),
                ("masterProductId", models.IntegerField(blank=True, null=True)),
                (
                    "masterProductName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("standardPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tierPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("costPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ecommerce", models.BooleanField()),
                ("active", models.BooleanField()),
                ("compositeProduct", models.BooleanField()),
                ("stateRestricted", models.BooleanField()),
                ("customerGroupRestricted", models.BooleanField()),
                ("categories", models.CharField(max_length=500)),
                ("trackInventory", models.BooleanField()),
                ("trackInventoryByImei", models.BooleanField()),
                ("insertedTimestamp", models.DateTimeField()),
                ("size", models.IntegerField()),
                ("returnable", models.BooleanField()),
                (
                    "minimumSellingPrice",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
