# Generated by Django 5.2.1 on 2025-05-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_product_eta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="insertedTimestamp",
        ),
    ]
