# Generated by Django 5.2.1 on 2025-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_insertedtimestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("imageUrl", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("insertedTimestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("categoryId", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("alias", models.CharField(max_length=255)),
                ("parentId", models.IntegerField(blank=True, null=True)),
                (
                    "parentIdStr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("imageUrl", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ecommerce", models.BooleanField()),
                ("customerSpecific", models.BooleanField()),
                ("loginRequired", models.BooleanField()),
                ("repairCategory", models.BooleanField()),
                ("businessTypeId", models.IntegerField(blank=True, null=True)),
                (
                    "businessTypeName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sequenceNumber", models.IntegerField()),
                ("metaTitle", models.CharField(blank=True, max_length=255, null=True)),
                ("metaData", models.TextField(blank=True, null=True)),
                ("metaDescription", models.TextField(blank=True, null=True)),
                ("deleted", models.BooleanField()),
                ("taxPaid", models.BooleanField()),
                ("lastSyncTimestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "businessTypeList",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="api.businesstype"
                    ),
                ),
                (
                    "subCategories",
                    models.ManyToManyField(
                        blank=True, related_name="parent_categories", to="api.category"
                    ),
                ),
            ],
        ),
    ]
