# Generated by Django 5.2.1 on 2025-05-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_businesstype_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subCategories",
        ),
    ]
