# Generated by Django 5.2.1 on 2025-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_category_subcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventoryData",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
