# Generated by Django 5.2.1 on 2025-05-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_product_inventorydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("productInventoryId", models.IntegerField()),
                ("productId", models.IntegerField()),
                ("wareHouseId", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("availableQuantity", models.IntegerField()),
                ("costPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("orderId", models.IntegerField(blank=True, null=True)),
                ("orderLineItemId", models.IntegerField(blank=True, null=True)),
                ("orderFulfillmentId", models.IntegerField(blank=True, null=True)),
                ("returnOrderId", models.IntegerField(blank=True, null=True)),
                ("purchaseOrderId", models.IntegerField(blank=True, null=True)),
                ("billId", models.IntegerField(blank=True, null=True)),
                ("transferOrderId", models.IntegerField(blank=True, null=True)),
                ("vendorReturnOrderId", models.IntegerField(blank=True, null=True)),
                ("compositeProductId", models.IntegerField(blank=True, null=True)),
                ("adjustmentId", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("actionType", models.CharField(blank=True, max_length=255, null=True)),
                ("salesOrderId", models.IntegerField(blank=True, null=True)),
                ("createdBy", models.IntegerField()),
                ("insertedTimestamp", models.DateTimeField()),
                (
                    "employeeName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("storeName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "warehouseName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="inventoryList",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="api.inventorydata"
            ),
        ),
    ]
