# Generated by Django 5.2.1 on 2025-05-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_inventorydata_product_inventorylist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventoryData",
        ),
    ]
