# Generated by Django 5.2.1 on 2025-05-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_product_inventorydata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorydata",
            name="productId",
            field=models.ForeignKey(
                db_column="productId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_records",
                to="api.product",
            ),
        ),
    ]
