# Generated by Django 5.2.1 on 2025-05-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_inventorydata_productid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("dbaName", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("stateId", models.IntegerField(blank=True, null=True)),
                ("stateName", models.CharField(blank=True, max_length=255, null=True)),
                ("zip", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("countryId", models.IntegerField(blank=True, null=True)),
                ("county", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("workPhone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("websiteUrl", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "websiteUsername",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "websitePassword",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "portalUserName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "portalPassword",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxId", models.CharField(blank=True, max_length=100, null=True)),
                ("feinNumber", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "dueAmount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "excessAmount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "storeCredit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("insuranceExpiryDate", models.DateField(blank=True, null=True)),
                ("manufacturerId", models.IntegerField(blank=True, null=True)),
                (
                    "manufacturerType",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("msaTypeId", models.IntegerField(blank=True, null=True)),
                (
                    "msaTypeName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paymentTermsId", models.IntegerField(blank=True, null=True)),
                (
                    "paymentTermsName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primarySalesRepresentativeId",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "primarySalesRepresentativeName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("createdBy", models.IntegerField(blank=True, null=True)),
                ("updatedBy", models.IntegerField(blank=True, null=True)),
                ("insertedTimestamp", models.DateTimeField(blank=True, null=True)),
                ("updatedTimestamp", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="TotalCostPriceAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="TotalQuantitySold",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="TotalRetailPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="TotalSaleAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
