# Generated by Django 5.2.1 on 2025-05-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_vendor_product_totalcostpriceamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="TotalGrossMargin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
