# Generated by Django 5.2.1 on 2025-05-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_product_totalgrossmargin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="TotalGrossMarginPrecentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
