# Generated by Django 5.0.2 on 2025-06-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_invoice_invoicelineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicelineitem",
            name="orderId",
            field=models.ForeignKey(
                db_column="orderId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="api.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="productId",
            field=models.ForeignKey(
                db_column="productId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_items",
                to="api.product",
            ),
        ),
    ]
