# Generated by Django 5.0.2 on 2025-06-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_invoicelineitem_orderid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="dbaName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
