# Generated by Django 5.0.2 on 2025-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_invoice_dbaname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="companyName",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customerName",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="dueAmount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="dueDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="insertedTimestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="orderNotes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="orderTags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="salesRepId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="salesRepName",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="shippingStatusId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="shippingStatusName",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="stateId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="storeName",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="totalAmount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="totalQuantity",
            field=models.IntegerField(default=0),
        ),
    ]
