# Generated by Django 5.0.2 on 2025-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_invoicelineitem_availablequantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="TotalCostPriceAmount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="TotalQuantitySold",
        ),
        migrations.RemoveField(
            model_name="product",
            name="TotalRetailPrice",
        ),
        migrations.AddField(
            model_name="product",
            name="TotalRevenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
