# Generated by Django 5.2.1 on 2025-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_product_totalcostpriceamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_categories_m2m",
            field=models.ManyToManyField(
                blank=True, related_name="products_m2m", to="api.category"
            ),
        ),
    ]
