# Generated by Django 5.2.1 on 2025-06-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_product_new_categories_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
    ]
