# Generated by Django 5.2.1 on 2025-06-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_product_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="new_categories_m2m",
            new_name="categories",
        ),
    ]
