# Generated by Django 5.2.1 on 2025-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_businesstype_lastsynctimestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="customerSpecific",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="deleted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="ecommerce",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="loginRequired",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="repairCategory",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="sequenceNumber",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="taxPaid",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
