# Generated by Django 5.2.1 on 2025-06-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_category_customerspecific_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "productName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upc", models.CharField(blank=True, max_length=50, null=True)),
                ("sku", models.CharField(blank=True, max_length=50, null=True)),
                ("totalQuantity", models.IntegerField(blank=True, null=True)),
                (
                    "totalQuantityStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "costPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costPriceStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "retailPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "retailPriceStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "discountAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discountAmountStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "taxAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "taxAmountStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "totalAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "totalAmountStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "grossMarginAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "grossMarginAmountStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "grossMarginPercentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "averagePrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "averagePriceStr",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("customerId", models.IntegerField(blank=True, null=True)),
                (
                    "customerIds",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customerName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("customerAddress", models.TextField(blank=True, null=True)),
                (
                    "customerState",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("customerNotes", models.TextField(blank=True, null=True)),
                (
                    "tobaccoTaxId",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("orderId", models.IntegerField(blank=True, null=True)),
                ("orderIds", models.CharField(blank=True, max_length=255, null=True)),
                ("returnOrderId", models.IntegerField(blank=True, null=True)),
                ("insertedTimestamp", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("returnOrderQuantity", models.IntegerField(blank=True, null=True)),
                ("recordType", models.CharField(blank=True, max_length=100, null=True)),
                ("masterRow", models.BooleanField(blank=True, null=True)),
                (
                    "csvDataType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("zip", models.CharField(blank=True, max_length=20, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("returnQuantity", models.IntegerField(blank=True, null=True)),
                (
                    "returnAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "returnCostPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("netQuantity", models.IntegerField(blank=True, null=True)),
                (
                    "netAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "netCostPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salesOrderId", models.IntegerField(blank=True, null=True)),
                (
                    "customerType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "productId",
                    models.ForeignKey(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_history",
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
