# Generated by Django 5.2.1 on 2025-06-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_purchasehistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PurchaseHistory",
        ),
    ]
