# Generated by Django 5.2.1 on 2025-06-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_delete_purchasehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchaseOrderId", models.IntegerField()),
                ("upc", models.CharField(max_length=50)),
                ("sku", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("purchasedQuantity", models.IntegerField()),
                ("passedQuantity", models.IntegerField()),
                ("failedQuantity", models.IntegerField()),
                ("costPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "totalCostPrice",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("vendorName", models.CharField(max_length=255)),
                ("billId", models.CharField(max_length=50)),
                ("purchaseOrderInsertedTimestamp", models.DateTimeField()),
                ("billInsertedTimestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "productId",
                    models.ForeignKey(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_history",
                        to="api.product",
                    ),
                ),
                (
                    "vendorId",
                    models.ForeignKey(
                        db_column="vendorId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_history",
                        to="api.vendor",
                    ),
                ),
            ],
        ),
    ]
