# Generated by Django 5.2.1 on 2025-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_purchasehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="billId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="costPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="failedQuantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="passedQuantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="purchaseOrderInsertedTimestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="purchasedQuantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="totalCostPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="upc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="vendorName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
