# Generated by Django 5.2.1 on 2025-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_purchasehistory_billid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="imageUrl",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
