# Generated by Django 5.2.1 on 2025-06-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_product_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="availableQuantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="compositeProduct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="costPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="customerGroupRestricted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="ecommerce",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="minimumSellingPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="returnable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="standardPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stateRestricted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tierPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="trackInventory",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="trackInventoryByImei",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="upc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
