# Generated by Django 5.2.1 on 2025-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_invoicelineitem_discounttype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesgentToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accessToken", models.TextField()),
                ("refreshToken", models.TextField(blank=True, null=True)),
                ("lastSyncTimestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
