# Generated by Django 5.2.1 on 2025-06-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_salesgenttoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "costPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "orderId",
                    models.ManyToManyField(
                        blank=True,
                        db_column="orderId",
                        related_name="product_history",
                        to="api.invoice",
                    ),
                ),
                (
                    "productId",
                    models.ForeignKey(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_history",
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
