# Generated by Django 5.2.1 on 2025-06-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_producthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producthistory",
            name="orderId",
        ),
    ]
