# Generated by Django 5.2.1 on 2025-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_producthistory_orderid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="insertedTimestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
