# Generated by Django 5.2.1 on 2025-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_invoice_insertedtimestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="producthistory",
            name="retailPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
