# Generated by Django 5.2.1 on 2025-06-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_producthistory_retailprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Unique identifier for the customer.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name or business name of the customer.",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="The customer's company name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dba_name",
                    models.CharField(
                        blank=True,
                        help_text="Doing Business As name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address.", max_length=255, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "inserted_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip", models.CharField(blank=True, max_length=20, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "billing_address1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billing_zip", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "billing_county",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "store_credit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("loyalty_points", models.IntegerField(default=0)),
                (
                    "due_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_terms_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sales_representative_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_sales_representative_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("taxable", models.BooleanField(default=False)),
                ("tax_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fein_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tobacco_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tobacco_license_expiration_date",
                    models.DateField(blank=True, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("notes2", models.TextField(blank=True, null=True)),
                (
                    "customer_store_address_list",
                    models.JSONField(blank=True, null=True),
                ),
                ("customer_document_list", models.JSONField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("store_id", models.IntegerField(blank=True, null=True)),
                ("tier", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
            },
        ),
    ]
