# Generated by Django 5.2.1 on 2025-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address2",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="billing_address1",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="billing_address2",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="billing_city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="billing_county",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="billing_state",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="billing_zip",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="county",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_document_list",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_store_address_list",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="dba_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="due_amount",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="fein_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="inserted_timestamp",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="loyalty_points",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="notes2",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="payment_terms_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="primary_sales_representative_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="sales_representative_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="state",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="store_credit",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="store_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tobacco_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tobacco_license_expiration_date",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="updated_timestamp",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="zip",
        ),
        migrations.AddField(
            model_name="customer",
            name="billingStateId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="communicateViaPhone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="communicateViaText",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="dbaName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="dueAmount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="excessAmount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="insertedTimestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="loyaltyPoints",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="rewardable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="salesRepresentativeName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="saveProductPrice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="sendDuePaymentReminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="stateId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="storeCredit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="storeId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="viewSpecificCategory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="viewSpecificProduct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
