# Generated by Django 5.2.1 on 2025-06-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_customer_address2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customerId",
            field=models.ForeignKey(
                blank=True,
                db_column="customerId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
    ]
