# Generated by Django 5.2.1 on 2025-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_invoice_customerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reportName", models.CharField(max_length=255, unique=True)),
                ("htmlContent", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
