# Generated by Django 5.2.3 on 2025-07-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_product_avgcostprice_product_boxquantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POLocal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("purchaseOrderId", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "totalAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "totalQuantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("insertedTimestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        db_column="vendorId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_local",
                        to="api.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="POLocalLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "unitPrice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "totalPrice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "po_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="api.polocal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_line_items",
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
