# Generated by Django 5.2.3 on 2025-07-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_polocal_polocallineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polocallineitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="po_line_items",
                to="api.product",
                unique=True,
            ),
        ),
    ]
