# Generated by Django 5.2.3 on 2025-07-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_polocallineitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polocallineitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="po_line_items",
                to="api.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="polocallineitem",
            unique_together={("po_local", "product")},
        ),
    ]
