# Generated by Django 5.2.3 on 2025-07-17 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_polocallineitem_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase", models.BooleanField(default=False)),
                ("tracker", models.BooleanField(default=False)),
                ("delivery", models.BooleanField(default=False)),
                ("catalog", models.BooleanField(default=False)),
                ("purchase_PO", models.BooleanField(default=False)),
                ("purchase_Inventory", models.BooleanField(default=False)),
                ("purchase_Settings", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
