# Generated by Django 5.2.3 on 2025-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_modulepermissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_Admin_Profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_Global_View",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_History",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_Map",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_Profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_Salesmen_List",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="tracker_config",
            field=models.BooleanField(default=False),
        ),
    ]
