# Generated by Django 5.2.3 on 2025-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_modulepermissions_tracker_admin_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepermissions",
            name="accounts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="utility",
            field=models.BooleanField(default=False),
        ),
    ]
