# Generated by Django 5.2.3 on 2025-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_modulepermissions_accounts_modulepermissions_utility"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepermissions",
            name="utility_product_sync",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulepermissions",
            name="utility_sticker",
            field=models.BooleanField(default=False),
        ),
    ]
