# Generated by Django 5.2.3 on 2025-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_modulepermissions_utility_product_sync_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepermissions",
            name="accounts_invoice",
            field=models.BooleanField(default=False),
        ),
    ]
