# Generated by Django 5.2.3 on 2025-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_modulepermissions_accounts_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulepermissions",
            name="delivery_admin",
            field=models.BooleanField(default=False),
        ),
    ]
