# Generated by Django 5.2.3 on 2025-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_modulepermissions_delivery_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isHotProduct",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
