# Generated by Django 5.2.3 on 2025-08-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_product_ishotproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventoryList",
        ),
        migrations.DeleteModel(
            name="InventoryData",
        ),
    ]
