# Generated by Django 5.2.3 on 2025-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_remove_product_inventorylist_delete_inventorydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parValueDays",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
