# Generated by Django 5.2.3 on 2025-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_category_parvaluedays"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isClearanceProduct",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
