# Generated by Django 5.2.1 on 2025-06-02 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_salesman_user_delete_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesman",
            options={"verbose_name": "Salesman", "verbose_name_plural": "Salesmen"},
        ),
        migrations.AddField(
            model_name="salesman",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="salesman",
            name="user_type",
            field=models.CharField(
                choices=[("salesman", "Salesman"), ("admin", "Admin")],
                default="salesman",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="salesman",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesmen",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
