# Generated by Django 5.2.1 on 2025-06-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_salesman_options_salesman_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Stone Mountain Gas Stations'", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_routes",
                        to="tracker.salesman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planned Route",
                "verbose_name_plural": "Planned Routes",
                "ordering": ["-date"],
                "unique_together": {("salesman", "date")},
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("order", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("visited", "Visited"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("visited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="tracker.plannedroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Stop",
                "verbose_name_plural": "Route Stops",
                "ordering": ["route", "order"],
            },
        ),
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("offline", "Went Offline"),
                            ("online", "Came Online"),
                            ("low_battery", "Low Battery"),
                            ("checkpoint", "Reached Checkpoint"),
                            ("route_start", "Started Route"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "salesman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tracker.salesman",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Notification",
                "verbose_name_plural": "System Notifications",
                "ordering": ["-timestamp"],
            },
        ),
    ]
