# Generated by Django 5.2.3 on 2025-08-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0049_modulepermissions_accounts_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driverName", models.CharField(max_length=100)),
                ("driverLicense", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truckNo", models.CharField(max_length=50)),
                ("truckName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DeliverySheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box", models.IntegerField()),
                (
                    "checkAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cashAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "insertedTimestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("deliveryTimestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.deliverydriver",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.invoice"
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.deliverytruck",
                    ),
                ),
            ],
        ),
    ]
