# Generated by Django 5.2.3 on 2025-08-06 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverydriver",
            name="driverName",
        ),
        migrations.AddField(
            model_name="deliverydriver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
