# Generated by Django 5.2.1 on 2025-06-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authAPI", "0003_alter_customuser_user_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
    ]
