# Generated by Django 5.2.1 on 2025-06-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authAPI", "0005_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
